# syntax=docker/dockerfile:1
FROM osrf/ros:noetic-desktop-full
RUN apt update
RUN apt install -y python3-catkin-pkg python-nose python-setuptools libgtest-dev build-essential git
RUN source /opt/ros/noetic/setup.bash
RUN mkdir -p ~/catkin_ws/src
RUN cd ~/catkin_ws/
RUN catkin_make
RUN cd src
RUN git clone https://github.com/Slamtec/rplidar_ros.git
RUN cd .. && catkin_make
