#!/bin/bash
xhost +local:docker
docker run -it     \
    --net=host \
    --env="DISPLAY" \
    --volume="$HOME/.Xauthority:/root/.Xauthority:rw" \
    --volume="/dev/ttyUSB0:/dev/ttyUSB0" \
    --privileged    \
    rplidar $@


